### ISSUE TITLE
Albums ought to be ordered differently

### ISSUE THREAD

**Issue by vvasuki** [Jagalite/Save-to-Google-Photos#3]
Currently, albums are alphabetically ordered - this is inconvenient if one has many albums. Instead, it might make sense to order albums in decreasing order of size in terms of number of photos.

**Comment by Jagalite** [comment]
I think the usefulness in the ordering of albums heavily depends on the users needs.

It would be inconvenient to try to find a particular album from say 20+ without it being in alphabetical order.

I don't quite see the benefit having the albums ordered by capacity. Maybe unless it will convey which albums are used the most. Anything I am missing?

**Comment by vvasuki** [comment]
> It would be inconvenient to try to find a particular album from say 20+ without it being in alphabetical order.

You're assuming here that the user is trying to find an album by some name he already has in his mind. This is not true in my case. I don't recall the exact name of most of my albums - Did I name it trees? or plants? Or वृक्षाः? In such a case scrolling up and down finding the album can be a pain.

> Maybe unless it will convey which albums are used the most.

Exactly. A user is more likely to be interested in albums he's used more in the past.

**Comment by Jagalite** [comment]
One of the thing about albums that have a lot of images is that they can mean anything. Sure I can see that albums with more images could mean that it's a favorite album, but it can also just mean that that album is filled with 200 photos of my trip to Canada.

Having it ordered by capacity would assume that the user only have albums for general things, "animals" instead of "cats","dogs","birds"... While it is great to be able to identify albums that fit a wide range of topics, I believe that if the use is opening the options menu, they are looking for a particular album. Unless it's their first time using the extension. Otherwise they probably already would have these"general" albums active.

**Comment by vvasuki** [comment]
>Unless it's their first time using the extension. Otherwise they probably already would have these"general" albums active.

Yes, this is but a one time thing and therefore low priority. The ordering can be up to the user (via some button in the options.)
